/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: appsrv.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "appsrv.pb-c.h"
void   appsrv_tx_data_req__init
                     (AppsrvTxDataReq         *message)
{
  static AppsrvTxDataReq init_value = APPSRV_TX_DATA_REQ__INIT;
  *message = init_value;
}
size_t appsrv_tx_data_req__get_packed_size
                     (const AppsrvTxDataReq *message)
{
  assert(message->base.descriptor == &appsrv_tx_data_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_tx_data_req__pack
                     (const AppsrvTxDataReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_tx_data_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_tx_data_req__pack_to_buffer
                     (const AppsrvTxDataReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_tx_data_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvTxDataReq *
       appsrv_tx_data_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvTxDataReq *)
     protobuf_c_message_unpack (&appsrv_tx_data_req__descriptor,
                                allocator, len, data);
}
void   appsrv_tx_data_req__free_unpacked
                     (AppsrvTxDataReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_tx_data_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_tx_data_cnf__init
                     (AppsrvTxDataCnf         *message)
{
  static AppsrvTxDataCnf init_value = APPSRV_TX_DATA_CNF__INIT;
  *message = init_value;
}
size_t appsrv_tx_data_cnf__get_packed_size
                     (const AppsrvTxDataCnf *message)
{
  assert(message->base.descriptor == &appsrv_tx_data_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_tx_data_cnf__pack
                     (const AppsrvTxDataCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_tx_data_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_tx_data_cnf__pack_to_buffer
                     (const AppsrvTxDataCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_tx_data_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvTxDataCnf *
       appsrv_tx_data_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvTxDataCnf *)
     protobuf_c_message_unpack (&appsrv_tx_data_cnf__descriptor,
                                allocator, len, data);
}
void   appsrv_tx_data_cnf__free_unpacked
                     (AppsrvTxDataCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_tx_data_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_set_join_permit_req__init
                     (AppsrvSetJoinPermitReq         *message)
{
  static AppsrvSetJoinPermitReq init_value = APPSRV_SET_JOIN_PERMIT_REQ__INIT;
  *message = init_value;
}
size_t appsrv_set_join_permit_req__get_packed_size
                     (const AppsrvSetJoinPermitReq *message)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_set_join_permit_req__pack
                     (const AppsrvSetJoinPermitReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_set_join_permit_req__pack_to_buffer
                     (const AppsrvSetJoinPermitReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvSetJoinPermitReq *
       appsrv_set_join_permit_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvSetJoinPermitReq *)
     protobuf_c_message_unpack (&appsrv_set_join_permit_req__descriptor,
                                allocator, len, data);
}
void   appsrv_set_join_permit_req__free_unpacked
                     (AppsrvSetJoinPermitReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_set_join_permit_cnf__init
                     (AppsrvSetJoinPermitCnf         *message)
{
  static AppsrvSetJoinPermitCnf init_value = APPSRV_SET_JOIN_PERMIT_CNF__INIT;
  *message = init_value;
}
size_t appsrv_set_join_permit_cnf__get_packed_size
                     (const AppsrvSetJoinPermitCnf *message)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_set_join_permit_cnf__pack
                     (const AppsrvSetJoinPermitCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_set_join_permit_cnf__pack_to_buffer
                     (const AppsrvSetJoinPermitCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvSetJoinPermitCnf *
       appsrv_set_join_permit_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvSetJoinPermitCnf *)
     protobuf_c_message_unpack (&appsrv_set_join_permit_cnf__descriptor,
                                allocator, len, data);
}
void   appsrv_set_join_permit_cnf__free_unpacked
                     (AppsrvSetJoinPermitCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_set_join_permit_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_device_update_ind__init
                     (AppsrvDeviceUpdateInd         *message)
{
  static AppsrvDeviceUpdateInd init_value = APPSRV_DEVICE_UPDATE_IND__INIT;
  *message = init_value;
}
size_t appsrv_device_update_ind__get_packed_size
                     (const AppsrvDeviceUpdateInd *message)
{
  assert(message->base.descriptor == &appsrv_device_update_ind__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_device_update_ind__pack
                     (const AppsrvDeviceUpdateInd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_device_update_ind__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_device_update_ind__pack_to_buffer
                     (const AppsrvDeviceUpdateInd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_device_update_ind__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvDeviceUpdateInd *
       appsrv_device_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvDeviceUpdateInd *)
     protobuf_c_message_unpack (&appsrv_device_update_ind__descriptor,
                                allocator, len, data);
}
void   appsrv_device_update_ind__free_unpacked
                     (AppsrvDeviceUpdateInd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_device_update_ind__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_device_not_active_update_ind__init
                     (AppsrvDeviceNotActiveUpdateInd         *message)
{
  static AppsrvDeviceNotActiveUpdateInd init_value = APPSRV_DEVICE_NOT_ACTIVE_UPDATE_IND__INIT;
  *message = init_value;
}
size_t appsrv_device_not_active_update_ind__get_packed_size
                     (const AppsrvDeviceNotActiveUpdateInd *message)
{
  assert(message->base.descriptor == &appsrv_device_not_active_update_ind__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_device_not_active_update_ind__pack
                     (const AppsrvDeviceNotActiveUpdateInd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_device_not_active_update_ind__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_device_not_active_update_ind__pack_to_buffer
                     (const AppsrvDeviceNotActiveUpdateInd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_device_not_active_update_ind__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvDeviceNotActiveUpdateInd *
       appsrv_device_not_active_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvDeviceNotActiveUpdateInd *)
     protobuf_c_message_unpack (&appsrv_device_not_active_update_ind__descriptor,
                                allocator, len, data);
}
void   appsrv_device_not_active_update_ind__free_unpacked
                     (AppsrvDeviceNotActiveUpdateInd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_device_not_active_update_ind__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_device_data_rx_ind__init
                     (AppsrvDeviceDataRxInd         *message)
{
  static AppsrvDeviceDataRxInd init_value = APPSRV_DEVICE_DATA_RX_IND__INIT;
  *message = init_value;
}
size_t appsrv_device_data_rx_ind__get_packed_size
                     (const AppsrvDeviceDataRxInd *message)
{
  assert(message->base.descriptor == &appsrv_device_data_rx_ind__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_device_data_rx_ind__pack
                     (const AppsrvDeviceDataRxInd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_device_data_rx_ind__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_device_data_rx_ind__pack_to_buffer
                     (const AppsrvDeviceDataRxInd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_device_data_rx_ind__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvDeviceDataRxInd *
       appsrv_device_data_rx_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvDeviceDataRxInd *)
     protobuf_c_message_unpack (&appsrv_device_data_rx_ind__descriptor,
                                allocator, len, data);
}
void   appsrv_device_data_rx_ind__free_unpacked
                     (AppsrvDeviceDataRxInd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_device_data_rx_ind__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_collector_state_cng_update_ind__init
                     (AppsrvCollectorStateCngUpdateInd         *message)
{
  static AppsrvCollectorStateCngUpdateInd init_value = APPSRV_COLLECTOR_STATE_CNG_UPDATE_IND__INIT;
  *message = init_value;
}
size_t appsrv_collector_state_cng_update_ind__get_packed_size
                     (const AppsrvCollectorStateCngUpdateInd *message)
{
  assert(message->base.descriptor == &appsrv_collector_state_cng_update_ind__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_collector_state_cng_update_ind__pack
                     (const AppsrvCollectorStateCngUpdateInd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_collector_state_cng_update_ind__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_collector_state_cng_update_ind__pack_to_buffer
                     (const AppsrvCollectorStateCngUpdateInd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_collector_state_cng_update_ind__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvCollectorStateCngUpdateInd *
       appsrv_collector_state_cng_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvCollectorStateCngUpdateInd *)
     protobuf_c_message_unpack (&appsrv_collector_state_cng_update_ind__descriptor,
                                allocator, len, data);
}
void   appsrv_collector_state_cng_update_ind__free_unpacked
                     (AppsrvCollectorStateCngUpdateInd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_collector_state_cng_update_ind__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_nwk_param__init
                     (AppsrvNwkParam         *message)
{
  static AppsrvNwkParam init_value = APPSRV_NWK_PARAM__INIT;
  *message = init_value;
}
size_t appsrv_nwk_param__get_packed_size
                     (const AppsrvNwkParam *message)
{
  assert(message->base.descriptor == &appsrv_nwk_param__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_nwk_param__pack
                     (const AppsrvNwkParam *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_nwk_param__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_nwk_param__pack_to_buffer
                     (const AppsrvNwkParam *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_nwk_param__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvNwkParam *
       appsrv_nwk_param__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvNwkParam *)
     protobuf_c_message_unpack (&appsrv_nwk_param__descriptor,
                                allocator, len, data);
}
void   appsrv_nwk_param__free_unpacked
                     (AppsrvNwkParam *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_nwk_param__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_nwk_info_update_ind__init
                     (AppsrvNwkInfoUpdateInd         *message)
{
  static AppsrvNwkInfoUpdateInd init_value = APPSRV_NWK_INFO_UPDATE_IND__INIT;
  *message = init_value;
}
size_t appsrv_nwk_info_update_ind__get_packed_size
                     (const AppsrvNwkInfoUpdateInd *message)
{
  assert(message->base.descriptor == &appsrv_nwk_info_update_ind__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_nwk_info_update_ind__pack
                     (const AppsrvNwkInfoUpdateInd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_nwk_info_update_ind__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_nwk_info_update_ind__pack_to_buffer
                     (const AppsrvNwkInfoUpdateInd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_nwk_info_update_ind__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvNwkInfoUpdateInd *
       appsrv_nwk_info_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvNwkInfoUpdateInd *)
     protobuf_c_message_unpack (&appsrv_nwk_info_update_ind__descriptor,
                                allocator, len, data);
}
void   appsrv_nwk_info_update_ind__free_unpacked
                     (AppsrvNwkInfoUpdateInd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_nwk_info_update_ind__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_get_nwk_info_req__init
                     (AppsrvGetNwkInfoReq         *message)
{
  static AppsrvGetNwkInfoReq init_value = APPSRV_GET_NWK_INFO_REQ__INIT;
  *message = init_value;
}
size_t appsrv_get_nwk_info_req__get_packed_size
                     (const AppsrvGetNwkInfoReq *message)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_get_nwk_info_req__pack
                     (const AppsrvGetNwkInfoReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_get_nwk_info_req__pack_to_buffer
                     (const AppsrvGetNwkInfoReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvGetNwkInfoReq *
       appsrv_get_nwk_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvGetNwkInfoReq *)
     protobuf_c_message_unpack (&appsrv_get_nwk_info_req__descriptor,
                                allocator, len, data);
}
void   appsrv_get_nwk_info_req__free_unpacked
                     (AppsrvGetNwkInfoReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_get_nwk_info_cnf__init
                     (AppsrvGetNwkInfoCnf         *message)
{
  static AppsrvGetNwkInfoCnf init_value = APPSRV_GET_NWK_INFO_CNF__INIT;
  *message = init_value;
}
size_t appsrv_get_nwk_info_cnf__get_packed_size
                     (const AppsrvGetNwkInfoCnf *message)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_get_nwk_info_cnf__pack
                     (const AppsrvGetNwkInfoCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_get_nwk_info_cnf__pack_to_buffer
                     (const AppsrvGetNwkInfoCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvGetNwkInfoCnf *
       appsrv_get_nwk_info_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvGetNwkInfoCnf *)
     protobuf_c_message_unpack (&appsrv_get_nwk_info_cnf__descriptor,
                                allocator, len, data);
}
void   appsrv_get_nwk_info_cnf__free_unpacked
                     (AppsrvGetNwkInfoCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_get_nwk_info_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_get_device_array_req__init
                     (AppsrvGetDeviceArrayReq         *message)
{
  static AppsrvGetDeviceArrayReq init_value = APPSRV_GET_DEVICE_ARRAY_REQ__INIT;
  *message = init_value;
}
size_t appsrv_get_device_array_req__get_packed_size
                     (const AppsrvGetDeviceArrayReq *message)
{
  assert(message->base.descriptor == &appsrv_get_device_array_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_get_device_array_req__pack
                     (const AppsrvGetDeviceArrayReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_get_device_array_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_get_device_array_req__pack_to_buffer
                     (const AppsrvGetDeviceArrayReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_get_device_array_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvGetDeviceArrayReq *
       appsrv_get_device_array_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvGetDeviceArrayReq *)
     protobuf_c_message_unpack (&appsrv_get_device_array_req__descriptor,
                                allocator, len, data);
}
void   appsrv_get_device_array_req__free_unpacked
                     (AppsrvGetDeviceArrayReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_get_device_array_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   appsrv_get_device_array_cnf__init
                     (AppsrvGetDeviceArrayCnf         *message)
{
  static AppsrvGetDeviceArrayCnf init_value = APPSRV_GET_DEVICE_ARRAY_CNF__INIT;
  *message = init_value;
}
size_t appsrv_get_device_array_cnf__get_packed_size
                     (const AppsrvGetDeviceArrayCnf *message)
{
  assert(message->base.descriptor == &appsrv_get_device_array_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t appsrv_get_device_array_cnf__pack
                     (const AppsrvGetDeviceArrayCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &appsrv_get_device_array_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t appsrv_get_device_array_cnf__pack_to_buffer
                     (const AppsrvGetDeviceArrayCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &appsrv_get_device_array_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AppsrvGetDeviceArrayCnf *
       appsrv_get_device_array_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AppsrvGetDeviceArrayCnf *)
     protobuf_c_message_unpack (&appsrv_get_device_array_cnf__descriptor,
                                allocator, len, data);
}
void   appsrv_get_device_array_cnf__free_unpacked
                     (AppsrvGetDeviceArrayCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &appsrv_get_device_array_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const AppsrvCmdId appsrv_tx_data_req__cmd_id__default_value = APPSRV__CMD_ID__APPSRV_TX_DATA_REQ;
static const ProtobufCFieldDescriptor appsrv_tx_data_req__field_descriptors[5] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvTxDataReq, cmdid),
    &appsrv__cmd_id__descriptor,
    &appsrv_tx_data_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvTxDataReq, msgid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "devDescriptor",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvTxDataReq, devdescriptor),
    &api_mac_device_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "configReqMsg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvTxDataReq, configreqmsg),
    &smsgs_config_req_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toggleLedReq",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvTxDataReq, toggleledreq),
    &smsgs_toggle_led_req_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_tx_data_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  3,   /* field[3] = configReqMsg */
  2,   /* field[2] = devDescriptor */
  1,   /* field[1] = msgId */
  4,   /* field[4] = toggleLedReq */
};
static const ProtobufCIntRange appsrv_tx_data_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor appsrv_tx_data_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_txDataReq",
  "AppsrvTxDataReq",
  "AppsrvTxDataReq",
  "",
  sizeof(AppsrvTxDataReq),
  5,
  appsrv_tx_data_req__field_descriptors,
  appsrv_tx_data_req__field_indices_by_name,
  1,  appsrv_tx_data_req__number_ranges,
  (ProtobufCMessageInit) appsrv_tx_data_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const AppsrvCmdId appsrv_tx_data_cnf__cmd_id__default_value = APPSRV__CMD_ID__APPSRV_TX_DATA_CNF;
static const ProtobufCFieldDescriptor appsrv_tx_data_cnf__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvTxDataCnf, cmdid),
    &appsrv__cmd_id__descriptor,
    &appsrv_tx_data_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvTxDataCnf, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_tx_data_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange appsrv_tx_data_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor appsrv_tx_data_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_txDataCnf",
  "AppsrvTxDataCnf",
  "AppsrvTxDataCnf",
  "",
  sizeof(AppsrvTxDataCnf),
  2,
  appsrv_tx_data_cnf__field_descriptors,
  appsrv_tx_data_cnf__field_indices_by_name,
  1,  appsrv_tx_data_cnf__number_ranges,
  (ProtobufCMessageInit) appsrv_tx_data_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const AppsrvCmdId appsrv_set_join_permit_req__cmd_id__default_value = APPSRV__CMD_ID__APPSRV_SET_JOIN_PERMIT_REQ;
static const ProtobufCFieldDescriptor appsrv_set_join_permit_req__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvSetJoinPermitReq, cmdid),
    &appsrv__cmd_id__descriptor,
    &appsrv_set_join_permit_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvSetJoinPermitReq, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_set_join_permit_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = duration */
};
static const ProtobufCIntRange appsrv_set_join_permit_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor appsrv_set_join_permit_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_setJoinPermitReq",
  "AppsrvSetJoinPermitReq",
  "AppsrvSetJoinPermitReq",
  "",
  sizeof(AppsrvSetJoinPermitReq),
  2,
  appsrv_set_join_permit_req__field_descriptors,
  appsrv_set_join_permit_req__field_indices_by_name,
  1,  appsrv_set_join_permit_req__number_ranges,
  (ProtobufCMessageInit) appsrv_set_join_permit_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor appsrv_set_join_permit_cnf__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvSetJoinPermitCnf, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_set_join_permit_cnf__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange appsrv_set_join_permit_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor appsrv_set_join_permit_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_setJoinPermitCnf",
  "AppsrvSetJoinPermitCnf",
  "AppsrvSetJoinPermitCnf",
  "",
  sizeof(AppsrvSetJoinPermitCnf),
  1,
  appsrv_set_join_permit_cnf__field_descriptors,
  appsrv_set_join_permit_cnf__field_indices_by_name,
  1,  appsrv_set_join_permit_cnf__number_ranges,
  (ProtobufCMessageInit) appsrv_set_join_permit_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor appsrv_device_update_ind__field_descriptors[2] =
{
  {
    "devDescriptor",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceUpdateInd, devdescriptor),
    &api_mac_device_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "devCapInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceUpdateInd, devcapinfo),
    &api_mac_capability_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_device_update_ind__field_indices_by_name[] = {
  1,   /* field[1] = devCapInfo */
  0,   /* field[0] = devDescriptor */
};
static const ProtobufCIntRange appsrv_device_update_ind__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor appsrv_device_update_ind__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_deviceUpdateInd",
  "AppsrvDeviceUpdateInd",
  "AppsrvDeviceUpdateInd",
  "",
  sizeof(AppsrvDeviceUpdateInd),
  2,
  appsrv_device_update_ind__field_descriptors,
  appsrv_device_update_ind__field_indices_by_name,
  1,  appsrv_device_update_ind__number_ranges,
  (ProtobufCMessageInit) appsrv_device_update_ind__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor appsrv_device_not_active_update_ind__field_descriptors[2] =
{
  {
    "devDescriptor",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceNotActiveUpdateInd, devdescriptor),
    &api_mac_device_descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceNotActiveUpdateInd, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_device_not_active_update_ind__field_indices_by_name[] = {
  0,   /* field[0] = devDescriptor */
  1,   /* field[1] = timeout */
};
static const ProtobufCIntRange appsrv_device_not_active_update_ind__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor appsrv_device_not_active_update_ind__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_deviceNotActiveUpdateInd",
  "AppsrvDeviceNotActiveUpdateInd",
  "AppsrvDeviceNotActiveUpdateInd",
  "",
  sizeof(AppsrvDeviceNotActiveUpdateInd),
  2,
  appsrv_device_not_active_update_ind__field_descriptors,
  appsrv_device_not_active_update_ind__field_indices_by_name,
  1,  appsrv_device_not_active_update_ind__number_ranges,
  (ProtobufCMessageInit) appsrv_device_not_active_update_ind__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor appsrv_device_data_rx_ind__field_descriptors[4] =
{
  {
    "srcAddr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceDataRxInd, srcaddr),
    &api_mac_s_addr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceDataRxInd, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sDataMsg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceDataRxInd, sdatamsg),
    &smsgs_sensor_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sConfigMsg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvDeviceDataRxInd, sconfigmsg),
    &smsgs_config_rsp_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_device_data_rx_ind__field_indices_by_name[] = {
  1,   /* field[1] = rssi */
  3,   /* field[3] = sConfigMsg */
  2,   /* field[2] = sDataMsg */
  0,   /* field[0] = srcAddr */
};
static const ProtobufCIntRange appsrv_device_data_rx_ind__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor appsrv_device_data_rx_ind__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_deviceDataRxInd",
  "AppsrvDeviceDataRxInd",
  "AppsrvDeviceDataRxInd",
  "",
  sizeof(AppsrvDeviceDataRxInd),
  4,
  appsrv_device_data_rx_ind__field_descriptors,
  appsrv_device_data_rx_ind__field_indices_by_name,
  2,  appsrv_device_data_rx_ind__number_ranges,
  (ProtobufCMessageInit) appsrv_device_data_rx_ind__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor appsrv_collector_state_cng_update_ind__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvCollectorStateCngUpdateInd, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_collector_state_cng_update_ind__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange appsrv_collector_state_cng_update_ind__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor appsrv_collector_state_cng_update_ind__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_collectorStateCngUpdateInd",
  "AppsrvCollectorStateCngUpdateInd",
  "AppsrvCollectorStateCngUpdateInd",
  "",
  sizeof(AppsrvCollectorStateCngUpdateInd),
  1,
  appsrv_collector_state_cng_update_ind__field_descriptors,
  appsrv_collector_state_cng_update_ind__field_indices_by_name,
  1,  appsrv_collector_state_cng_update_ind__number_ranges,
  (ProtobufCMessageInit) appsrv_collector_state_cng_update_ind__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor appsrv_nwk_param__field_descriptors[4] =
{
  {
    "nwkInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvNwkParam, nwkinfo),
    &llc_net_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "securityEnabled",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvNwkParam, securityenabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "networkMode",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvNwkParam, networkmode),
    &nwk_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvNwkParam, state),
    &cllc_states__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_nwk_param__field_indices_by_name[] = {
  2,   /* field[2] = networkMode */
  0,   /* field[0] = nwkInfo */
  1,   /* field[1] = securityEnabled */
  3,   /* field[3] = state */
};
static const ProtobufCIntRange appsrv_nwk_param__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor appsrv_nwk_param__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_nwkParam",
  "AppsrvNwkParam",
  "AppsrvNwkParam",
  "",
  sizeof(AppsrvNwkParam),
  4,
  appsrv_nwk_param__field_descriptors,
  appsrv_nwk_param__field_indices_by_name,
  1,  appsrv_nwk_param__number_ranges,
  (ProtobufCMessageInit) appsrv_nwk_param__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor appsrv_nwk_info_update_ind__field_descriptors[1] =
{
  {
    "nwkinfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvNwkInfoUpdateInd, nwkinfo),
    &appsrv_nwk_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_nwk_info_update_ind__field_indices_by_name[] = {
  0,   /* field[0] = nwkinfo */
};
static const ProtobufCIntRange appsrv_nwk_info_update_ind__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor appsrv_nwk_info_update_ind__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_nwkInfoUpdateInd",
  "AppsrvNwkInfoUpdateInd",
  "AppsrvNwkInfoUpdateInd",
  "",
  sizeof(AppsrvNwkInfoUpdateInd),
  1,
  appsrv_nwk_info_update_ind__field_descriptors,
  appsrv_nwk_info_update_ind__field_indices_by_name,
  1,  appsrv_nwk_info_update_ind__number_ranges,
  (ProtobufCMessageInit) appsrv_nwk_info_update_ind__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const AppsrvCmdId appsrv_get_nwk_info_req__cmd_id__default_value = APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_REQ;
static const ProtobufCFieldDescriptor appsrv_get_nwk_info_req__field_descriptors[1] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvGetNwkInfoReq, cmdid),
    &appsrv__cmd_id__descriptor,
    &appsrv_get_nwk_info_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_get_nwk_info_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
};
static const ProtobufCIntRange appsrv_get_nwk_info_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor appsrv_get_nwk_info_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_getNwkInfoReq",
  "AppsrvGetNwkInfoReq",
  "AppsrvGetNwkInfoReq",
  "",
  sizeof(AppsrvGetNwkInfoReq),
  1,
  appsrv_get_nwk_info_req__field_descriptors,
  appsrv_get_nwk_info_req__field_indices_by_name,
  1,  appsrv_get_nwk_info_req__number_ranges,
  (ProtobufCMessageInit) appsrv_get_nwk_info_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const AppsrvCmdId appsrv_get_nwk_info_cnf__cmd_id__default_value = APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_CNF;
static const ProtobufCFieldDescriptor appsrv_get_nwk_info_cnf__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvGetNwkInfoCnf, cmdid),
    &appsrv__cmd_id__descriptor,
    &appsrv_get_nwk_info_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvGetNwkInfoCnf, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nwkinfo",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AppsrvGetNwkInfoCnf, nwkinfo),
    &appsrv_nwk_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_get_nwk_info_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = nwkinfo */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange appsrv_get_nwk_info_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor appsrv_get_nwk_info_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_getNwkInfoCnf",
  "AppsrvGetNwkInfoCnf",
  "AppsrvGetNwkInfoCnf",
  "",
  sizeof(AppsrvGetNwkInfoCnf),
  3,
  appsrv_get_nwk_info_cnf__field_descriptors,
  appsrv_get_nwk_info_cnf__field_indices_by_name,
  1,  appsrv_get_nwk_info_cnf__number_ranges,
  (ProtobufCMessageInit) appsrv_get_nwk_info_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const AppsrvCmdId appsrv_get_device_array_req__cmd_id__default_value = APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_REQ;
static const ProtobufCFieldDescriptor appsrv_get_device_array_req__field_descriptors[1] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvGetDeviceArrayReq, cmdid),
    &appsrv__cmd_id__descriptor,
    &appsrv_get_device_array_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_get_device_array_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
};
static const ProtobufCIntRange appsrv_get_device_array_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor appsrv_get_device_array_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_getDeviceArrayReq",
  "AppsrvGetDeviceArrayReq",
  "AppsrvGetDeviceArrayReq",
  "",
  sizeof(AppsrvGetDeviceArrayReq),
  1,
  appsrv_get_device_array_req__field_descriptors,
  appsrv_get_device_array_req__field_indices_by_name,
  1,  appsrv_get_device_array_req__number_ranges,
  (ProtobufCMessageInit) appsrv_get_device_array_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const AppsrvCmdId appsrv_get_device_array_cnf__cmd_id__default_value = APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_CNF;
static const ProtobufCFieldDescriptor appsrv_get_device_array_cnf__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AppsrvGetDeviceArrayCnf, cmdid),
    &appsrv__cmd_id__descriptor,
    &appsrv_get_device_array_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AppsrvGetDeviceArrayCnf, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "devInfo",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AppsrvGetDeviceArrayCnf, n_devinfo),
    offsetof(AppsrvGetDeviceArrayCnf, devinfo),
    &csf_device_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned appsrv_get_device_array_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = devInfo */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange appsrv_get_device_array_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor appsrv_get_device_array_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "appsrv_getDeviceArrayCnf",
  "AppsrvGetDeviceArrayCnf",
  "AppsrvGetDeviceArrayCnf",
  "",
  sizeof(AppsrvGetDeviceArrayCnf),
  3,
  appsrv_get_device_array_cnf__field_descriptors,
  appsrv_get_device_array_cnf__field_indices_by_name,
  1,  appsrv_get_device_array_cnf__number_ranges,
  (ProtobufCMessageInit) appsrv_get_device_array_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue timac_app_srv_sys_id__enum_values_by_number[1] =
{
  { "RPC_SYS_PB_TIMAC_APPSRV", "TIMAC_APP_SRV_SYS_ID__RPC_SYS_PB_TIMAC_APPSRV", 10 },
};
static const ProtobufCIntRange timac_app_srv_sys_id__value_ranges[] = {
{10, 0},{0, 1}
};
static const ProtobufCEnumValueIndex timac_app_srv_sys_id__enum_values_by_name[1] =
{
  { "RPC_SYS_PB_TIMAC_APPSRV", 0 },
};
const ProtobufCEnumDescriptor timac_app_srv_sys_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "timacAppSrvSysId",
  "timacAppSrvSysId",
  "TimacAppSrvSysId",
  "",
  1,
  timac_app_srv_sys_id__enum_values_by_number,
  1,
  timac_app_srv_sys_id__enum_values_by_name,
  1,
  timac_app_srv_sys_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue appsrv__cmd_id__enum_values_by_number[15] =
{
  { "APPSRV_DEVICE_JOINED_IND", "APPSRV__CMD_ID__APPSRV_DEVICE_JOINED_IND", 1 },
  { "APPSRV_DEVICE_LEFT_IND", "APPSRV__CMD_ID__APPSRV_DEVICE_LEFT_IND", 2 },
  { "APPSRV_NWK_INFO_IND", "APPSRV__CMD_ID__APPSRV_NWK_INFO_IND", 3 },
  { "APPSRV_GET_NWK_INFO_REQ", "APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_REQ", 4 },
  { "APPSRV_GET_NWK_INFO_RSP", "APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_RSP", 5 },
  { "APPSRV_GET_NWK_INFO_CNF", "APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_CNF", 6 },
  { "APPSRV_GET_DEVICE_ARRAY_REQ", "APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_REQ", 7 },
  { "APPSRV_GET_DEVICE_ARRAY_CNF", "APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_CNF", 8 },
  { "APPSRV_DEVICE_NOTACTIVE_UPDATE_IND", "APPSRV__CMD_ID__APPSRV_DEVICE_NOTACTIVE_UPDATE_IND", 9 },
  { "APPSRV_DEVICE_DATA_RX_IND", "APPSRV__CMD_ID__APPSRV_DEVICE_DATA_RX_IND", 10 },
  { "APPSRV_COLLECTOR_STATE_CNG_IND", "APPSRV__CMD_ID__APPSRV_COLLECTOR_STATE_CNG_IND", 11 },
  { "APPSRV_SET_JOIN_PERMIT_REQ", "APPSRV__CMD_ID__APPSRV_SET_JOIN_PERMIT_REQ", 12 },
  { "APPSRV_SET_JOIN_PERMIT_CNF", "APPSRV__CMD_ID__APPSRV_SET_JOIN_PERMIT_CNF", 13 },
  { "APPSRV_TX_DATA_REQ", "APPSRV__CMD_ID__APPSRV_TX_DATA_REQ", 14 },
  { "APPSRV_TX_DATA_CNF", "APPSRV__CMD_ID__APPSRV_TX_DATA_CNF", 15 },
};
static const ProtobufCIntRange appsrv__cmd_id__value_ranges[] = {
{1, 0},{0, 15}
};
static const ProtobufCEnumValueIndex appsrv__cmd_id__enum_values_by_name[15] =
{
  { "APPSRV_COLLECTOR_STATE_CNG_IND", 10 },
  { "APPSRV_DEVICE_DATA_RX_IND", 9 },
  { "APPSRV_DEVICE_JOINED_IND", 0 },
  { "APPSRV_DEVICE_LEFT_IND", 1 },
  { "APPSRV_DEVICE_NOTACTIVE_UPDATE_IND", 8 },
  { "APPSRV_GET_DEVICE_ARRAY_CNF", 7 },
  { "APPSRV_GET_DEVICE_ARRAY_REQ", 6 },
  { "APPSRV_GET_NWK_INFO_CNF", 5 },
  { "APPSRV_GET_NWK_INFO_REQ", 3 },
  { "APPSRV_GET_NWK_INFO_RSP", 4 },
  { "APPSRV_NWK_INFO_IND", 2 },
  { "APPSRV_SET_JOIN_PERMIT_CNF", 12 },
  { "APPSRV_SET_JOIN_PERMIT_REQ", 11 },
  { "APPSRV_TX_DATA_CNF", 14 },
  { "APPSRV_TX_DATA_REQ", 13 },
};
const ProtobufCEnumDescriptor appsrv__cmd_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "appsrv_CmdId",
  "appsrv_CmdId",
  "AppsrvCmdId",
  "",
  15,
  appsrv__cmd_id__enum_values_by_number,
  15,
  appsrv__cmd_id__enum_values_by_name,
  1,
  appsrv__cmd_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue nwk_mode__enum_values_by_number[3] =
{
  { "BEACON_ENABLED", "NWK_MODE__BEACON_ENABLED", 1 },
  { "NON_BEACON", "NWK_MODE__NON_BEACON", 2 },
  { "FREQUENCY_HOPPING", "NWK_MODE__FREQUENCY_HOPPING", 3 },
};
static const ProtobufCIntRange nwk_mode__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex nwk_mode__enum_values_by_name[3] =
{
  { "BEACON_ENABLED", 0 },
  { "FREQUENCY_HOPPING", 2 },
  { "NON_BEACON", 1 },
};
const ProtobufCEnumDescriptor nwk_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nwkMode",
  "nwkMode",
  "NwkMode",
  "",
  3,
  nwk_mode__enum_values_by_number,
  3,
  nwk_mode__enum_values_by_name,
  1,
  nwk_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
