/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: appsrv.proto */

#ifndef PROTOBUF_C_appsrv_2eproto__INCLUDED
#define PROTOBUF_C_appsrv_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "smsgs.pb-c.h"
#include "api_mac.pb-c.h"
#include "llc.pb-c.h"
#include "cllc.pb-c.h"
#include "csf.pb-c.h"

typedef struct _AppsrvTxDataReq AppsrvTxDataReq;
typedef struct _AppsrvTxDataCnf AppsrvTxDataCnf;
typedef struct _AppsrvSetJoinPermitReq AppsrvSetJoinPermitReq;
typedef struct _AppsrvSetJoinPermitCnf AppsrvSetJoinPermitCnf;
typedef struct _AppsrvDeviceUpdateInd AppsrvDeviceUpdateInd;
typedef struct _AppsrvDeviceNotActiveUpdateInd AppsrvDeviceNotActiveUpdateInd;
typedef struct _AppsrvDeviceDataRxInd AppsrvDeviceDataRxInd;
typedef struct _AppsrvCollectorStateCngUpdateInd AppsrvCollectorStateCngUpdateInd;
typedef struct _AppsrvNwkParam AppsrvNwkParam;
typedef struct _AppsrvNwkInfoUpdateInd AppsrvNwkInfoUpdateInd;
typedef struct _AppsrvGetNwkInfoReq AppsrvGetNwkInfoReq;
typedef struct _AppsrvGetNwkInfoCnf AppsrvGetNwkInfoCnf;
typedef struct _AppsrvGetDeviceArrayReq AppsrvGetDeviceArrayReq;
typedef struct _AppsrvGetDeviceArrayCnf AppsrvGetDeviceArrayCnf;


/* --- enums --- */

/*
 * MT System ID for TIMAC APP Server Interface Protobuf sub-system ID 
 */
typedef enum _TimacAppSrvSysId {
  TIMAC_APP_SRV_SYS_ID__RPC_SYS_PB_TIMAC_APPSRV = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TIMAC_APP_SRV_SYS_ID)
} TimacAppSrvSysId;
/*
 * Command IDs - each of these are associated with Request, 
 * Responses, Indications, and Confirm messages 
 */
typedef enum _AppsrvCmdId {
  APPSRV__CMD_ID__APPSRV_DEVICE_JOINED_IND = 1,
  APPSRV__CMD_ID__APPSRV_DEVICE_LEFT_IND = 2,
  APPSRV__CMD_ID__APPSRV_NWK_INFO_IND = 3,
  APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_REQ = 4,
  APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_RSP = 5,
  APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_CNF = 6,
  APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_REQ = 7,
  APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_CNF = 8,
  APPSRV__CMD_ID__APPSRV_DEVICE_NOTACTIVE_UPDATE_IND = 9,
  APPSRV__CMD_ID__APPSRV_DEVICE_DATA_RX_IND = 10,
  APPSRV__CMD_ID__APPSRV_COLLECTOR_STATE_CNG_IND = 11,
  APPSRV__CMD_ID__APPSRV_SET_JOIN_PERMIT_REQ = 12,
  APPSRV__CMD_ID__APPSRV_SET_JOIN_PERMIT_CNF = 13,
  APPSRV__CMD_ID__APPSRV_TX_DATA_REQ = 14,
  APPSRV__CMD_ID__APPSRV_TX_DATA_CNF = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(APPSRV__CMD_ID)
} AppsrvCmdId;
typedef enum _NwkMode {
  NWK_MODE__BEACON_ENABLED = 1,
  NWK_MODE__NON_BEACON = 2,
  NWK_MODE__FREQUENCY_HOPPING = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_MODE)
} NwkMode;

/* --- messages --- */

/*
 * APPSRV_TX_DATA_REQ
 */
struct  _AppsrvTxDataReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  AppsrvCmdId cmdid;
  SmsgsCmdIds msgid;
  ApiMacDeviceDescriptor *devdescriptor;
  SmsgsConfigReqMsg *configreqmsg;
  SmsgsToggleLedReqMsg *toggleledreq;
};
#define APPSRV_TX_DATA_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_tx_data_req__descriptor) \
    , APPSRV__CMD_ID__APPSRV_TX_DATA_REQ, 0, NULL, NULL, NULL }


/*
 *APPSRV_TX_DATA_CNF
 */
struct  _AppsrvTxDataCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  AppsrvCmdId cmdid;
  int32_t status;
};
#define APPSRV_TX_DATA_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_tx_data_cnf__descriptor) \
    , APPSRV__CMD_ID__APPSRV_TX_DATA_CNF, 0 }


/*
 * APPSRV_SET_JOIN_PERMIT_REQ
 */
struct  _AppsrvSetJoinPermitReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  AppsrvCmdId cmdid;
  /*
   *   duration - duration for join permit to be turned on in
   *              milliseconds.
   *              0 sets it Off, 0xFFFFFFFF sets it ON indefinitely
   *              Any other non zero value sets it on for that duration * 
   */
  int32_t duration;
};
#define APPSRV_SET_JOIN_PERMIT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_set_join_permit_req__descriptor) \
    , APPSRV__CMD_ID__APPSRV_SET_JOIN_PERMIT_REQ, 0 }


/*
 * APPSRV_SET_JOIN_PERMIT_CNF
 */
struct  _AppsrvSetJoinPermitCnf
{
  ProtobufCMessage base;
  /*
   * provides the result of processing of the 
   * APPSRV_SET_JOIN_PERMIT_REQ message
   */
  int32_t status;
};
#define APPSRV_SET_JOIN_PERMIT_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_set_join_permit_cnf__descriptor) \
    , 0 }


/*
 * APPSRV_DEVICE_JOINED_IND
 */
struct  _AppsrvDeviceUpdateInd
{
  ProtobufCMessage base;
  ApiMacDeviceDescriptor *devdescriptor;
  ApiMacCapabilityInfo *devcapinfo;
};
#define APPSRV_DEVICE_UPDATE_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_device_update_ind__descriptor) \
    , NULL, NULL }


/*
 * APPSRV_DEVICE_NOTACTIVE_UPDATE_IND
 */
struct  _AppsrvDeviceNotActiveUpdateInd
{
  ProtobufCMessage base;
  ApiMacDeviceDescriptor *devdescriptor;
  uint32_t timeout;
};
#define APPSRV_DEVICE_NOT_ACTIVE_UPDATE_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_device_not_active_update_ind__descriptor) \
    , NULL, 0 }


/*
 * APPSRV_DEVICE_DATA_RX_IND
 */
struct  _AppsrvDeviceDataRxInd
{
  ProtobufCMessage base;
  ApiMacSAddr *srcaddr;
  int32_t rssi;
  SmsgsSensorMsg *sdatamsg;
  SmsgsConfigRspMsg *sconfigmsg;
};
#define APPSRV_DEVICE_DATA_RX_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_device_data_rx_ind__descriptor) \
    , NULL, 0, NULL, NULL }


struct  _AppsrvCollectorStateCngUpdateInd
{
  ProtobufCMessage base;
  uint32_t state;
};
#define APPSRV_COLLECTOR_STATE_CNG_UPDATE_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_collector_state_cng_update_ind__descriptor) \
    , 0 }


/*
 * sub-message for the network parameters
 * used by appsrv_nwkInfoUpdateInd 
 * and appsrv_getNwkInfoCnf
 */
struct  _AppsrvNwkParam
{
  ProtobufCMessage base;
  LlcNetInfo *nwkinfo;
  int32_t securityenabled;
  NwkMode networkmode;
  CllcStates state;
};
#define APPSRV_NWK_PARAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_nwk_param__descriptor) \
    , NULL, 0, 0, 0 }


struct  _AppsrvNwkInfoUpdateInd
{
  ProtobufCMessage base;
  AppsrvNwkParam *nwkinfo;
};
#define APPSRV_NWK_INFO_UPDATE_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_nwk_info_update_ind__descriptor) \
    , NULL }


/*
 * APPSRV_GET_NWK_INFO_REQ
 */
struct  _AppsrvGetNwkInfoReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  AppsrvCmdId cmdid;
};
#define APPSRV_GET_NWK_INFO_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_get_nwk_info_req__descriptor) \
    , APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_REQ }


/*
 * APPSRV_GET_NWK_INFO_CNF
 */
struct  _AppsrvGetNwkInfoCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  AppsrvCmdId cmdid;
  uint32_t status;
  AppsrvNwkParam *nwkinfo;
};
#define APPSRV_GET_NWK_INFO_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_get_nwk_info_cnf__descriptor) \
    , APPSRV__CMD_ID__APPSRV_GET_NWK_INFO_CNF, 0, NULL }


/*
 * APPSRV_GET_DEVICE_ARRAY_REQ
 */
struct  _AppsrvGetDeviceArrayReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  AppsrvCmdId cmdid;
};
#define APPSRV_GET_DEVICE_ARRAY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_get_device_array_req__descriptor) \
    , APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_REQ }


/*
 * APPSRV_GET_DEVICE_ARRAY_CNF
 */
struct  _AppsrvGetDeviceArrayCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  AppsrvCmdId cmdid;
  uint32_t status;
  size_t n_devinfo;
  CsfDeviceInformation **devinfo;
};
#define APPSRV_GET_DEVICE_ARRAY_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&appsrv_get_device_array_cnf__descriptor) \
    , APPSRV__CMD_ID__APPSRV_GET_DEVICE_ARRAY_CNF, 0, 0,NULL }


/* AppsrvTxDataReq methods */
void   appsrv_tx_data_req__init
                     (AppsrvTxDataReq         *message);
size_t appsrv_tx_data_req__get_packed_size
                     (const AppsrvTxDataReq   *message);
size_t appsrv_tx_data_req__pack
                     (const AppsrvTxDataReq   *message,
                      uint8_t             *out);
size_t appsrv_tx_data_req__pack_to_buffer
                     (const AppsrvTxDataReq   *message,
                      ProtobufCBuffer     *buffer);
AppsrvTxDataReq *
       appsrv_tx_data_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_tx_data_req__free_unpacked
                     (AppsrvTxDataReq *message,
                      ProtobufCAllocator *allocator);
/* AppsrvTxDataCnf methods */
void   appsrv_tx_data_cnf__init
                     (AppsrvTxDataCnf         *message);
size_t appsrv_tx_data_cnf__get_packed_size
                     (const AppsrvTxDataCnf   *message);
size_t appsrv_tx_data_cnf__pack
                     (const AppsrvTxDataCnf   *message,
                      uint8_t             *out);
size_t appsrv_tx_data_cnf__pack_to_buffer
                     (const AppsrvTxDataCnf   *message,
                      ProtobufCBuffer     *buffer);
AppsrvTxDataCnf *
       appsrv_tx_data_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_tx_data_cnf__free_unpacked
                     (AppsrvTxDataCnf *message,
                      ProtobufCAllocator *allocator);
/* AppsrvSetJoinPermitReq methods */
void   appsrv_set_join_permit_req__init
                     (AppsrvSetJoinPermitReq         *message);
size_t appsrv_set_join_permit_req__get_packed_size
                     (const AppsrvSetJoinPermitReq   *message);
size_t appsrv_set_join_permit_req__pack
                     (const AppsrvSetJoinPermitReq   *message,
                      uint8_t             *out);
size_t appsrv_set_join_permit_req__pack_to_buffer
                     (const AppsrvSetJoinPermitReq   *message,
                      ProtobufCBuffer     *buffer);
AppsrvSetJoinPermitReq *
       appsrv_set_join_permit_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_set_join_permit_req__free_unpacked
                     (AppsrvSetJoinPermitReq *message,
                      ProtobufCAllocator *allocator);
/* AppsrvSetJoinPermitCnf methods */
void   appsrv_set_join_permit_cnf__init
                     (AppsrvSetJoinPermitCnf         *message);
size_t appsrv_set_join_permit_cnf__get_packed_size
                     (const AppsrvSetJoinPermitCnf   *message);
size_t appsrv_set_join_permit_cnf__pack
                     (const AppsrvSetJoinPermitCnf   *message,
                      uint8_t             *out);
size_t appsrv_set_join_permit_cnf__pack_to_buffer
                     (const AppsrvSetJoinPermitCnf   *message,
                      ProtobufCBuffer     *buffer);
AppsrvSetJoinPermitCnf *
       appsrv_set_join_permit_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_set_join_permit_cnf__free_unpacked
                     (AppsrvSetJoinPermitCnf *message,
                      ProtobufCAllocator *allocator);
/* AppsrvDeviceUpdateInd methods */
void   appsrv_device_update_ind__init
                     (AppsrvDeviceUpdateInd         *message);
size_t appsrv_device_update_ind__get_packed_size
                     (const AppsrvDeviceUpdateInd   *message);
size_t appsrv_device_update_ind__pack
                     (const AppsrvDeviceUpdateInd   *message,
                      uint8_t             *out);
size_t appsrv_device_update_ind__pack_to_buffer
                     (const AppsrvDeviceUpdateInd   *message,
                      ProtobufCBuffer     *buffer);
AppsrvDeviceUpdateInd *
       appsrv_device_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_device_update_ind__free_unpacked
                     (AppsrvDeviceUpdateInd *message,
                      ProtobufCAllocator *allocator);
/* AppsrvDeviceNotActiveUpdateInd methods */
void   appsrv_device_not_active_update_ind__init
                     (AppsrvDeviceNotActiveUpdateInd         *message);
size_t appsrv_device_not_active_update_ind__get_packed_size
                     (const AppsrvDeviceNotActiveUpdateInd   *message);
size_t appsrv_device_not_active_update_ind__pack
                     (const AppsrvDeviceNotActiveUpdateInd   *message,
                      uint8_t             *out);
size_t appsrv_device_not_active_update_ind__pack_to_buffer
                     (const AppsrvDeviceNotActiveUpdateInd   *message,
                      ProtobufCBuffer     *buffer);
AppsrvDeviceNotActiveUpdateInd *
       appsrv_device_not_active_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_device_not_active_update_ind__free_unpacked
                     (AppsrvDeviceNotActiveUpdateInd *message,
                      ProtobufCAllocator *allocator);
/* AppsrvDeviceDataRxInd methods */
void   appsrv_device_data_rx_ind__init
                     (AppsrvDeviceDataRxInd         *message);
size_t appsrv_device_data_rx_ind__get_packed_size
                     (const AppsrvDeviceDataRxInd   *message);
size_t appsrv_device_data_rx_ind__pack
                     (const AppsrvDeviceDataRxInd   *message,
                      uint8_t             *out);
size_t appsrv_device_data_rx_ind__pack_to_buffer
                     (const AppsrvDeviceDataRxInd   *message,
                      ProtobufCBuffer     *buffer);
AppsrvDeviceDataRxInd *
       appsrv_device_data_rx_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_device_data_rx_ind__free_unpacked
                     (AppsrvDeviceDataRxInd *message,
                      ProtobufCAllocator *allocator);
/* AppsrvCollectorStateCngUpdateInd methods */
void   appsrv_collector_state_cng_update_ind__init
                     (AppsrvCollectorStateCngUpdateInd         *message);
size_t appsrv_collector_state_cng_update_ind__get_packed_size
                     (const AppsrvCollectorStateCngUpdateInd   *message);
size_t appsrv_collector_state_cng_update_ind__pack
                     (const AppsrvCollectorStateCngUpdateInd   *message,
                      uint8_t             *out);
size_t appsrv_collector_state_cng_update_ind__pack_to_buffer
                     (const AppsrvCollectorStateCngUpdateInd   *message,
                      ProtobufCBuffer     *buffer);
AppsrvCollectorStateCngUpdateInd *
       appsrv_collector_state_cng_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_collector_state_cng_update_ind__free_unpacked
                     (AppsrvCollectorStateCngUpdateInd *message,
                      ProtobufCAllocator *allocator);
/* AppsrvNwkParam methods */
void   appsrv_nwk_param__init
                     (AppsrvNwkParam         *message);
size_t appsrv_nwk_param__get_packed_size
                     (const AppsrvNwkParam   *message);
size_t appsrv_nwk_param__pack
                     (const AppsrvNwkParam   *message,
                      uint8_t             *out);
size_t appsrv_nwk_param__pack_to_buffer
                     (const AppsrvNwkParam   *message,
                      ProtobufCBuffer     *buffer);
AppsrvNwkParam *
       appsrv_nwk_param__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_nwk_param__free_unpacked
                     (AppsrvNwkParam *message,
                      ProtobufCAllocator *allocator);
/* AppsrvNwkInfoUpdateInd methods */
void   appsrv_nwk_info_update_ind__init
                     (AppsrvNwkInfoUpdateInd         *message);
size_t appsrv_nwk_info_update_ind__get_packed_size
                     (const AppsrvNwkInfoUpdateInd   *message);
size_t appsrv_nwk_info_update_ind__pack
                     (const AppsrvNwkInfoUpdateInd   *message,
                      uint8_t             *out);
size_t appsrv_nwk_info_update_ind__pack_to_buffer
                     (const AppsrvNwkInfoUpdateInd   *message,
                      ProtobufCBuffer     *buffer);
AppsrvNwkInfoUpdateInd *
       appsrv_nwk_info_update_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_nwk_info_update_ind__free_unpacked
                     (AppsrvNwkInfoUpdateInd *message,
                      ProtobufCAllocator *allocator);
/* AppsrvGetNwkInfoReq methods */
void   appsrv_get_nwk_info_req__init
                     (AppsrvGetNwkInfoReq         *message);
size_t appsrv_get_nwk_info_req__get_packed_size
                     (const AppsrvGetNwkInfoReq   *message);
size_t appsrv_get_nwk_info_req__pack
                     (const AppsrvGetNwkInfoReq   *message,
                      uint8_t             *out);
size_t appsrv_get_nwk_info_req__pack_to_buffer
                     (const AppsrvGetNwkInfoReq   *message,
                      ProtobufCBuffer     *buffer);
AppsrvGetNwkInfoReq *
       appsrv_get_nwk_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_get_nwk_info_req__free_unpacked
                     (AppsrvGetNwkInfoReq *message,
                      ProtobufCAllocator *allocator);
/* AppsrvGetNwkInfoCnf methods */
void   appsrv_get_nwk_info_cnf__init
                     (AppsrvGetNwkInfoCnf         *message);
size_t appsrv_get_nwk_info_cnf__get_packed_size
                     (const AppsrvGetNwkInfoCnf   *message);
size_t appsrv_get_nwk_info_cnf__pack
                     (const AppsrvGetNwkInfoCnf   *message,
                      uint8_t             *out);
size_t appsrv_get_nwk_info_cnf__pack_to_buffer
                     (const AppsrvGetNwkInfoCnf   *message,
                      ProtobufCBuffer     *buffer);
AppsrvGetNwkInfoCnf *
       appsrv_get_nwk_info_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_get_nwk_info_cnf__free_unpacked
                     (AppsrvGetNwkInfoCnf *message,
                      ProtobufCAllocator *allocator);
/* AppsrvGetDeviceArrayReq methods */
void   appsrv_get_device_array_req__init
                     (AppsrvGetDeviceArrayReq         *message);
size_t appsrv_get_device_array_req__get_packed_size
                     (const AppsrvGetDeviceArrayReq   *message);
size_t appsrv_get_device_array_req__pack
                     (const AppsrvGetDeviceArrayReq   *message,
                      uint8_t             *out);
size_t appsrv_get_device_array_req__pack_to_buffer
                     (const AppsrvGetDeviceArrayReq   *message,
                      ProtobufCBuffer     *buffer);
AppsrvGetDeviceArrayReq *
       appsrv_get_device_array_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_get_device_array_req__free_unpacked
                     (AppsrvGetDeviceArrayReq *message,
                      ProtobufCAllocator *allocator);
/* AppsrvGetDeviceArrayCnf methods */
void   appsrv_get_device_array_cnf__init
                     (AppsrvGetDeviceArrayCnf         *message);
size_t appsrv_get_device_array_cnf__get_packed_size
                     (const AppsrvGetDeviceArrayCnf   *message);
size_t appsrv_get_device_array_cnf__pack
                     (const AppsrvGetDeviceArrayCnf   *message,
                      uint8_t             *out);
size_t appsrv_get_device_array_cnf__pack_to_buffer
                     (const AppsrvGetDeviceArrayCnf   *message,
                      ProtobufCBuffer     *buffer);
AppsrvGetDeviceArrayCnf *
       appsrv_get_device_array_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   appsrv_get_device_array_cnf__free_unpacked
                     (AppsrvGetDeviceArrayCnf *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AppsrvTxDataReq_Closure)
                 (const AppsrvTxDataReq *message,
                  void *closure_data);
typedef void (*AppsrvTxDataCnf_Closure)
                 (const AppsrvTxDataCnf *message,
                  void *closure_data);
typedef void (*AppsrvSetJoinPermitReq_Closure)
                 (const AppsrvSetJoinPermitReq *message,
                  void *closure_data);
typedef void (*AppsrvSetJoinPermitCnf_Closure)
                 (const AppsrvSetJoinPermitCnf *message,
                  void *closure_data);
typedef void (*AppsrvDeviceUpdateInd_Closure)
                 (const AppsrvDeviceUpdateInd *message,
                  void *closure_data);
typedef void (*AppsrvDeviceNotActiveUpdateInd_Closure)
                 (const AppsrvDeviceNotActiveUpdateInd *message,
                  void *closure_data);
typedef void (*AppsrvDeviceDataRxInd_Closure)
                 (const AppsrvDeviceDataRxInd *message,
                  void *closure_data);
typedef void (*AppsrvCollectorStateCngUpdateInd_Closure)
                 (const AppsrvCollectorStateCngUpdateInd *message,
                  void *closure_data);
typedef void (*AppsrvNwkParam_Closure)
                 (const AppsrvNwkParam *message,
                  void *closure_data);
typedef void (*AppsrvNwkInfoUpdateInd_Closure)
                 (const AppsrvNwkInfoUpdateInd *message,
                  void *closure_data);
typedef void (*AppsrvGetNwkInfoReq_Closure)
                 (const AppsrvGetNwkInfoReq *message,
                  void *closure_data);
typedef void (*AppsrvGetNwkInfoCnf_Closure)
                 (const AppsrvGetNwkInfoCnf *message,
                  void *closure_data);
typedef void (*AppsrvGetDeviceArrayReq_Closure)
                 (const AppsrvGetDeviceArrayReq *message,
                  void *closure_data);
typedef void (*AppsrvGetDeviceArrayCnf_Closure)
                 (const AppsrvGetDeviceArrayCnf *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    timac_app_srv_sys_id__descriptor;
extern const ProtobufCEnumDescriptor    appsrv__cmd_id__descriptor;
extern const ProtobufCEnumDescriptor    nwk_mode__descriptor;
extern const ProtobufCMessageDescriptor appsrv_tx_data_req__descriptor;
extern const ProtobufCMessageDescriptor appsrv_tx_data_cnf__descriptor;
extern const ProtobufCMessageDescriptor appsrv_set_join_permit_req__descriptor;
extern const ProtobufCMessageDescriptor appsrv_set_join_permit_cnf__descriptor;
extern const ProtobufCMessageDescriptor appsrv_device_update_ind__descriptor;
extern const ProtobufCMessageDescriptor appsrv_device_not_active_update_ind__descriptor;
extern const ProtobufCMessageDescriptor appsrv_device_data_rx_ind__descriptor;
extern const ProtobufCMessageDescriptor appsrv_collector_state_cng_update_ind__descriptor;
extern const ProtobufCMessageDescriptor appsrv_nwk_param__descriptor;
extern const ProtobufCMessageDescriptor appsrv_nwk_info_update_ind__descriptor;
extern const ProtobufCMessageDescriptor appsrv_get_nwk_info_req__descriptor;
extern const ProtobufCMessageDescriptor appsrv_get_nwk_info_cnf__descriptor;
extern const ProtobufCMessageDescriptor appsrv_get_device_array_req__descriptor;
extern const ProtobufCMessageDescriptor appsrv_get_device_array_cnf__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_appsrv_2eproto__INCLUDED */
