/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: smsgs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "smsgs.pb-c.h"
void   smsgs_config_req_msg__init
                     (SmsgsConfigReqMsg         *message)
{
  static SmsgsConfigReqMsg init_value = SMSGS_CONFIG_REQ_MSG__INIT;
  *message = init_value;
}
size_t smsgs_config_req_msg__get_packed_size
                     (const SmsgsConfigReqMsg *message)
{
  assert(message->base.descriptor == &smsgs_config_req_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_config_req_msg__pack
                     (const SmsgsConfigReqMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_config_req_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_config_req_msg__pack_to_buffer
                     (const SmsgsConfigReqMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_config_req_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsConfigReqMsg *
       smsgs_config_req_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsConfigReqMsg *)
     protobuf_c_message_unpack (&smsgs_config_req_msg__descriptor,
                                allocator, len, data);
}
void   smsgs_config_req_msg__free_unpacked
                     (SmsgsConfigReqMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_config_req_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_config_rsp_msg__init
                     (SmsgsConfigRspMsg         *message)
{
  static SmsgsConfigRspMsg init_value = SMSGS_CONFIG_RSP_MSG__INIT;
  *message = init_value;
}
size_t smsgs_config_rsp_msg__get_packed_size
                     (const SmsgsConfigRspMsg *message)
{
  assert(message->base.descriptor == &smsgs_config_rsp_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_config_rsp_msg__pack
                     (const SmsgsConfigRspMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_config_rsp_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_config_rsp_msg__pack_to_buffer
                     (const SmsgsConfigRspMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_config_rsp_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsConfigRspMsg *
       smsgs_config_rsp_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsConfigRspMsg *)
     protobuf_c_message_unpack (&smsgs_config_rsp_msg__descriptor,
                                allocator, len, data);
}
void   smsgs_config_rsp_msg__free_unpacked
                     (SmsgsConfigRspMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_config_rsp_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_tracking_req_msg__init
                     (SmsgsTrackingReqMsg         *message)
{
  static SmsgsTrackingReqMsg init_value = SMSGS_TRACKING_REQ_MSG__INIT;
  *message = init_value;
}
size_t smsgs_tracking_req_msg__get_packed_size
                     (const SmsgsTrackingReqMsg *message)
{
  assert(message->base.descriptor == &smsgs_tracking_req_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_tracking_req_msg__pack
                     (const SmsgsTrackingReqMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_tracking_req_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_tracking_req_msg__pack_to_buffer
                     (const SmsgsTrackingReqMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_tracking_req_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsTrackingReqMsg *
       smsgs_tracking_req_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsTrackingReqMsg *)
     protobuf_c_message_unpack (&smsgs_tracking_req_msg__descriptor,
                                allocator, len, data);
}
void   smsgs_tracking_req_msg__free_unpacked
                     (SmsgsTrackingReqMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_tracking_req_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_tracking_rsp_msg__init
                     (SmsgsTrackingRspMsg         *message)
{
  static SmsgsTrackingRspMsg init_value = SMSGS_TRACKING_RSP_MSG__INIT;
  *message = init_value;
}
size_t smsgs_tracking_rsp_msg__get_packed_size
                     (const SmsgsTrackingRspMsg *message)
{
  assert(message->base.descriptor == &smsgs_tracking_rsp_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_tracking_rsp_msg__pack
                     (const SmsgsTrackingRspMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_tracking_rsp_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_tracking_rsp_msg__pack_to_buffer
                     (const SmsgsTrackingRspMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_tracking_rsp_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsTrackingRspMsg *
       smsgs_tracking_rsp_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsTrackingRspMsg *)
     protobuf_c_message_unpack (&smsgs_tracking_rsp_msg__descriptor,
                                allocator, len, data);
}
void   smsgs_tracking_rsp_msg__free_unpacked
                     (SmsgsTrackingRspMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_tracking_rsp_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_toggle_led_req_msg__init
                     (SmsgsToggleLedReqMsg         *message)
{
  static SmsgsToggleLedReqMsg init_value = SMSGS_TOGGLE_LED_REQ_MSG__INIT;
  *message = init_value;
}
size_t smsgs_toggle_led_req_msg__get_packed_size
                     (const SmsgsToggleLedReqMsg *message)
{
  assert(message->base.descriptor == &smsgs_toggle_led_req_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_toggle_led_req_msg__pack
                     (const SmsgsToggleLedReqMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_toggle_led_req_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_toggle_led_req_msg__pack_to_buffer
                     (const SmsgsToggleLedReqMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_toggle_led_req_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsToggleLedReqMsg *
       smsgs_toggle_led_req_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsToggleLedReqMsg *)
     protobuf_c_message_unpack (&smsgs_toggle_led_req_msg__descriptor,
                                allocator, len, data);
}
void   smsgs_toggle_led_req_msg__free_unpacked
                     (SmsgsToggleLedReqMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_toggle_led_req_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_toggle_led_rsp_msg__init
                     (SmsgsToggleLedRspMsg         *message)
{
  static SmsgsToggleLedRspMsg init_value = SMSGS_TOGGLE_LED_RSP_MSG__INIT;
  *message = init_value;
}
size_t smsgs_toggle_led_rsp_msg__get_packed_size
                     (const SmsgsToggleLedRspMsg *message)
{
  assert(message->base.descriptor == &smsgs_toggle_led_rsp_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_toggle_led_rsp_msg__pack
                     (const SmsgsToggleLedRspMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_toggle_led_rsp_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_toggle_led_rsp_msg__pack_to_buffer
                     (const SmsgsToggleLedRspMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_toggle_led_rsp_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsToggleLedRspMsg *
       smsgs_toggle_led_rsp_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsToggleLedRspMsg *)
     protobuf_c_message_unpack (&smsgs_toggle_led_rsp_msg__descriptor,
                                allocator, len, data);
}
void   smsgs_toggle_led_rsp_msg__free_unpacked
                     (SmsgsToggleLedRspMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_toggle_led_rsp_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_temp_sensor_field__init
                     (SmsgsTempSensorField         *message)
{
  static SmsgsTempSensorField init_value = SMSGS_TEMP_SENSOR_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_temp_sensor_field__get_packed_size
                     (const SmsgsTempSensorField *message)
{
  assert(message->base.descriptor == &smsgs_temp_sensor_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_temp_sensor_field__pack
                     (const SmsgsTempSensorField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_temp_sensor_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_temp_sensor_field__pack_to_buffer
                     (const SmsgsTempSensorField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_temp_sensor_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsTempSensorField *
       smsgs_temp_sensor_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsTempSensorField *)
     protobuf_c_message_unpack (&smsgs_temp_sensor_field__descriptor,
                                allocator, len, data);
}
void   smsgs_temp_sensor_field__free_unpacked
                     (SmsgsTempSensorField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_temp_sensor_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_light_sensor_field__init
                     (SmsgsLightSensorField         *message)
{
  static SmsgsLightSensorField init_value = SMSGS_LIGHT_SENSOR_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_light_sensor_field__get_packed_size
                     (const SmsgsLightSensorField *message)
{
  assert(message->base.descriptor == &smsgs_light_sensor_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_light_sensor_field__pack
                     (const SmsgsLightSensorField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_light_sensor_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_light_sensor_field__pack_to_buffer
                     (const SmsgsLightSensorField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_light_sensor_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsLightSensorField *
       smsgs_light_sensor_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsLightSensorField *)
     protobuf_c_message_unpack (&smsgs_light_sensor_field__descriptor,
                                allocator, len, data);
}
void   smsgs_light_sensor_field__free_unpacked
                     (SmsgsLightSensorField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_light_sensor_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_humidity_sensor_field__init
                     (SmsgsHumiditySensorField         *message)
{
  static SmsgsHumiditySensorField init_value = SMSGS_HUMIDITY_SENSOR_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_humidity_sensor_field__get_packed_size
                     (const SmsgsHumiditySensorField *message)
{
  assert(message->base.descriptor == &smsgs_humidity_sensor_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_humidity_sensor_field__pack
                     (const SmsgsHumiditySensorField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_humidity_sensor_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_humidity_sensor_field__pack_to_buffer
                     (const SmsgsHumiditySensorField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_humidity_sensor_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsHumiditySensorField *
       smsgs_humidity_sensor_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsHumiditySensorField *)
     protobuf_c_message_unpack (&smsgs_humidity_sensor_field__descriptor,
                                allocator, len, data);
}
void   smsgs_humidity_sensor_field__free_unpacked
                     (SmsgsHumiditySensorField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_humidity_sensor_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_pressure_sensor_field__init
                     (SmsgsPressureSensorField         *message)
{
  static SmsgsPressureSensorField init_value = SMSGS_PRESSURE_SENSOR_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_pressure_sensor_field__get_packed_size
                     (const SmsgsPressureSensorField *message)
{
  assert(message->base.descriptor == &smsgs_pressure_sensor_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_pressure_sensor_field__pack
                     (const SmsgsPressureSensorField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_pressure_sensor_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_pressure_sensor_field__pack_to_buffer
                     (const SmsgsPressureSensorField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_pressure_sensor_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsPressureSensorField *
       smsgs_pressure_sensor_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsPressureSensorField *)
     protobuf_c_message_unpack (&smsgs_pressure_sensor_field__descriptor,
                                allocator, len, data);
}
void   smsgs_pressure_sensor_field__free_unpacked
                     (SmsgsPressureSensorField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_pressure_sensor_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_motion_sensor_field__init
                     (SmsgsMotionSensorField         *message)
{
  static SmsgsMotionSensorField init_value = SMSGS_MOTION_SENSOR_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_motion_sensor_field__get_packed_size
                     (const SmsgsMotionSensorField *message)
{
  assert(message->base.descriptor == &smsgs_motion_sensor_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_motion_sensor_field__pack
                     (const SmsgsMotionSensorField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_motion_sensor_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_motion_sensor_field__pack_to_buffer
                     (const SmsgsMotionSensorField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_motion_sensor_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsMotionSensorField *
       smsgs_motion_sensor_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsMotionSensorField *)
     protobuf_c_message_unpack (&smsgs_motion_sensor_field__descriptor,
                                allocator, len, data);
}
void   smsgs_motion_sensor_field__free_unpacked
                     (SmsgsMotionSensorField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_motion_sensor_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_battery_sensor_field__init
                     (SmsgsBatterySensorField         *message)
{
  static SmsgsBatterySensorField init_value = SMSGS_BATTERY_SENSOR_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_battery_sensor_field__get_packed_size
                     (const SmsgsBatterySensorField *message)
{
  assert(message->base.descriptor == &smsgs_battery_sensor_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_battery_sensor_field__pack
                     (const SmsgsBatterySensorField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_battery_sensor_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_battery_sensor_field__pack_to_buffer
                     (const SmsgsBatterySensorField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_battery_sensor_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsBatterySensorField *
       smsgs_battery_sensor_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsBatterySensorField *)
     protobuf_c_message_unpack (&smsgs_battery_sensor_field__descriptor,
                                allocator, len, data);
}
void   smsgs_battery_sensor_field__free_unpacked
                     (SmsgsBatterySensorField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_battery_sensor_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_msg_stats_field__init
                     (SmsgsMsgStatsField         *message)
{
  static SmsgsMsgStatsField init_value = SMSGS_MSG_STATS_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_msg_stats_field__get_packed_size
                     (const SmsgsMsgStatsField *message)
{
  assert(message->base.descriptor == &smsgs_msg_stats_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_msg_stats_field__pack
                     (const SmsgsMsgStatsField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_msg_stats_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_msg_stats_field__pack_to_buffer
                     (const SmsgsMsgStatsField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_msg_stats_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsMsgStatsField *
       smsgs_msg_stats_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsMsgStatsField *)
     protobuf_c_message_unpack (&smsgs_msg_stats_field__descriptor,
                                allocator, len, data);
}
void   smsgs_msg_stats_field__free_unpacked
                     (SmsgsMsgStatsField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_msg_stats_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_config_settings_field__init
                     (SmsgsConfigSettingsField         *message)
{
  static SmsgsConfigSettingsField init_value = SMSGS_CONFIG_SETTINGS_FIELD__INIT;
  *message = init_value;
}
size_t smsgs_config_settings_field__get_packed_size
                     (const SmsgsConfigSettingsField *message)
{
  assert(message->base.descriptor == &smsgs_config_settings_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_config_settings_field__pack
                     (const SmsgsConfigSettingsField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_config_settings_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_config_settings_field__pack_to_buffer
                     (const SmsgsConfigSettingsField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_config_settings_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsConfigSettingsField *
       smsgs_config_settings_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsConfigSettingsField *)
     protobuf_c_message_unpack (&smsgs_config_settings_field__descriptor,
                                allocator, len, data);
}
void   smsgs_config_settings_field__free_unpacked
                     (SmsgsConfigSettingsField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_config_settings_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smsgs_sensor_msg__init
                     (SmsgsSensorMsg         *message)
{
  static SmsgsSensorMsg init_value = SMSGS_SENSOR_MSG__INIT;
  *message = init_value;
}
size_t smsgs_sensor_msg__get_packed_size
                     (const SmsgsSensorMsg *message)
{
  assert(message->base.descriptor == &smsgs_sensor_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smsgs_sensor_msg__pack
                     (const SmsgsSensorMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smsgs_sensor_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smsgs_sensor_msg__pack_to_buffer
                     (const SmsgsSensorMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smsgs_sensor_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmsgsSensorMsg *
       smsgs_sensor_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmsgsSensorMsg *)
     protobuf_c_message_unpack (&smsgs_sensor_msg__descriptor,
                                allocator, len, data);
}
void   smsgs_sensor_msg__free_unpacked
                     (SmsgsSensorMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &smsgs_sensor_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor smsgs_config_req_msg__field_descriptors[4] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigReqMsg, cmdid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frameControl",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigReqMsg, framecontrol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reportingInterval",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigReqMsg, reportinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pollingInterval",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigReqMsg, pollinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_config_req_msg__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = frameControl */
  3,   /* field[3] = pollingInterval */
  2,   /* field[2] = reportingInterval */
};
static const ProtobufCIntRange smsgs_config_req_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor smsgs_config_req_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_configReqMsg",
  "SmsgsConfigReqMsg",
  "SmsgsConfigReqMsg",
  "",
  sizeof(SmsgsConfigReqMsg),
  4,
  smsgs_config_req_msg__field_descriptors,
  smsgs_config_req_msg__field_indices_by_name,
  1,  smsgs_config_req_msg__number_ranges,
  (ProtobufCMessageInit) smsgs_config_req_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_config_rsp_msg__field_descriptors[5] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigRspMsg, cmdid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigRspMsg, status),
    &smsgs_status_values__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frameControl",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigRspMsg, framecontrol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "treportingInterval",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigRspMsg, treportinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pollingInterval",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigRspMsg, pollinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_config_rsp_msg__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = frameControl */
  4,   /* field[4] = pollingInterval */
  1,   /* field[1] = status */
  3,   /* field[3] = treportingInterval */
};
static const ProtobufCIntRange smsgs_config_rsp_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor smsgs_config_rsp_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_configRspMsg",
  "SmsgsConfigRspMsg",
  "SmsgsConfigRspMsg",
  "",
  sizeof(SmsgsConfigRspMsg),
  5,
  smsgs_config_rsp_msg__field_descriptors,
  smsgs_config_rsp_msg__field_indices_by_name,
  1,  smsgs_config_rsp_msg__number_ranges,
  (ProtobufCMessageInit) smsgs_config_rsp_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_tracking_req_msg__field_descriptors[1] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsTrackingReqMsg, cmdid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_tracking_req_msg__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
};
static const ProtobufCIntRange smsgs_tracking_req_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor smsgs_tracking_req_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_trackingReqMsg",
  "SmsgsTrackingReqMsg",
  "SmsgsTrackingReqMsg",
  "",
  sizeof(SmsgsTrackingReqMsg),
  1,
  smsgs_tracking_req_msg__field_descriptors,
  smsgs_tracking_req_msg__field_indices_by_name,
  1,  smsgs_tracking_req_msg__number_ranges,
  (ProtobufCMessageInit) smsgs_tracking_req_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_tracking_rsp_msg__field_descriptors[1] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsTrackingRspMsg, cmdid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_tracking_rsp_msg__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
};
static const ProtobufCIntRange smsgs_tracking_rsp_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor smsgs_tracking_rsp_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_trackingRspMsg",
  "SmsgsTrackingRspMsg",
  "SmsgsTrackingRspMsg",
  "",
  sizeof(SmsgsTrackingRspMsg),
  1,
  smsgs_tracking_rsp_msg__field_descriptors,
  smsgs_tracking_rsp_msg__field_indices_by_name,
  1,  smsgs_tracking_rsp_msg__number_ranges,
  (ProtobufCMessageInit) smsgs_tracking_rsp_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_toggle_led_req_msg__field_descriptors[1] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsToggleLedReqMsg, cmdid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_toggle_led_req_msg__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
};
static const ProtobufCIntRange smsgs_toggle_led_req_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor smsgs_toggle_led_req_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_toggleLedReqMsg",
  "SmsgsToggleLedReqMsg",
  "SmsgsToggleLedReqMsg",
  "",
  sizeof(SmsgsToggleLedReqMsg),
  1,
  smsgs_toggle_led_req_msg__field_descriptors,
  smsgs_toggle_led_req_msg__field_indices_by_name,
  1,  smsgs_toggle_led_req_msg__number_ranges,
  (ProtobufCMessageInit) smsgs_toggle_led_req_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_toggle_led_rsp_msg__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsToggleLedRspMsg, cmdid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledState",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsToggleLedRspMsg, ledstate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_toggle_led_rsp_msg__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = ledState */
};
static const ProtobufCIntRange smsgs_toggle_led_rsp_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor smsgs_toggle_led_rsp_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_toggleLedRspMsg",
  "SmsgsToggleLedRspMsg",
  "SmsgsToggleLedRspMsg",
  "",
  sizeof(SmsgsToggleLedRspMsg),
  2,
  smsgs_toggle_led_rsp_msg__field_descriptors,
  smsgs_toggle_led_rsp_msg__field_indices_by_name,
  1,  smsgs_toggle_led_rsp_msg__number_ranges,
  (ProtobufCMessageInit) smsgs_toggle_led_rsp_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_temp_sensor_field__field_descriptors[2] =
{
  {
    "ambienceTemp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsTempSensorField, ambiencetemp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "objectTemp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsTempSensorField, objecttemp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_temp_sensor_field__field_indices_by_name[] = {
  0,   /* field[0] = ambienceTemp */
  1,   /* field[1] = objectTemp */
};
static const ProtobufCIntRange smsgs_temp_sensor_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor smsgs_temp_sensor_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_tempSensorField",
  "SmsgsTempSensorField",
  "SmsgsTempSensorField",
  "",
  sizeof(SmsgsTempSensorField),
  2,
  smsgs_temp_sensor_field__field_descriptors,
  smsgs_temp_sensor_field__field_indices_by_name,
  1,  smsgs_temp_sensor_field__number_ranges,
  (ProtobufCMessageInit) smsgs_temp_sensor_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_light_sensor_field__field_descriptors[1] =
{
  {
    "rawData",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsLightSensorField, rawdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_light_sensor_field__field_indices_by_name[] = {
  0,   /* field[0] = rawData */
};
static const ProtobufCIntRange smsgs_light_sensor_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor smsgs_light_sensor_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_lightSensorField",
  "SmsgsLightSensorField",
  "SmsgsLightSensorField",
  "",
  sizeof(SmsgsLightSensorField),
  1,
  smsgs_light_sensor_field__field_descriptors,
  smsgs_light_sensor_field__field_indices_by_name,
  1,  smsgs_light_sensor_field__number_ranges,
  (ProtobufCMessageInit) smsgs_light_sensor_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_humidity_sensor_field__field_descriptors[2] =
{
  {
    "temp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsHumiditySensorField, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsHumiditySensorField, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_humidity_sensor_field__field_indices_by_name[] = {
  1,   /* field[1] = humidity */
  0,   /* field[0] = temp */
};
static const ProtobufCIntRange smsgs_humidity_sensor_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor smsgs_humidity_sensor_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_humiditySensorField",
  "SmsgsHumiditySensorField",
  "SmsgsHumiditySensorField",
  "",
  sizeof(SmsgsHumiditySensorField),
  2,
  smsgs_humidity_sensor_field__field_descriptors,
  smsgs_humidity_sensor_field__field_indices_by_name,
  1,  smsgs_humidity_sensor_field__number_ranges,
  (ProtobufCMessageInit) smsgs_humidity_sensor_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_pressure_sensor_field__field_descriptors[2] =
{
  {
    "tempValue",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsPressureSensorField, tempvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressureValue",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsPressureSensorField, pressurevalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_pressure_sensor_field__field_indices_by_name[] = {
  1,   /* field[1] = pressureValue */
  0,   /* field[0] = tempValue */
};
static const ProtobufCIntRange smsgs_pressure_sensor_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor smsgs_pressure_sensor_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_pressureSensorField",
  "SmsgsPressureSensorField",
  "SmsgsPressureSensorField",
  "",
  sizeof(SmsgsPressureSensorField),
  2,
  smsgs_pressure_sensor_field__field_descriptors,
  smsgs_pressure_sensor_field__field_indices_by_name,
  1,  smsgs_pressure_sensor_field__number_ranges,
  (ProtobufCMessageInit) smsgs_pressure_sensor_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_motion_sensor_field__field_descriptors[1] =
{
  {
    "isMotion",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SmsgsMotionSensorField, ismotion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_motion_sensor_field__field_indices_by_name[] = {
  0,   /* field[0] = isMotion */
};
static const ProtobufCIntRange smsgs_motion_sensor_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor smsgs_motion_sensor_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_motionSensorField",
  "SmsgsMotionSensorField",
  "SmsgsMotionSensorField",
  "",
  sizeof(SmsgsMotionSensorField),
  1,
  smsgs_motion_sensor_field__field_descriptors,
  smsgs_motion_sensor_field__field_indices_by_name,
  1,  smsgs_motion_sensor_field__number_ranges,
  (ProtobufCMessageInit) smsgs_motion_sensor_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_battery_sensor_field__field_descriptors[1] =
{
  {
    "voltageValue",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsBatterySensorField, voltagevalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_battery_sensor_field__field_indices_by_name[] = {
  0,   /* field[0] = voltageValue */
};
static const ProtobufCIntRange smsgs_battery_sensor_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor smsgs_battery_sensor_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_batterySensorField",
  "SmsgsBatterySensorField",
  "SmsgsBatterySensorField",
  "",
  sizeof(SmsgsBatterySensorField),
  1,
  smsgs_battery_sensor_field__field_descriptors,
  smsgs_battery_sensor_field__field_indices_by_name,
  1,  smsgs_battery_sensor_field__number_ranges,
  (ProtobufCMessageInit) smsgs_battery_sensor_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_msg_stats_field__field_descriptors[11] =
{
  {
    "joinAttempts",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, joinattempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "joinFails",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, joinfails),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgsAttempted",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, msgsattempted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgsSent",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, msgssent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trackingRequests",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, trackingrequests),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trackingResponseAttempts",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, trackingresponseattempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trackingResponseSent",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, trackingresponsesent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channelAccessFailures",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, channelaccessfailures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "macAckFailures",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, macackfailures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "otherDataRequestFailures",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, otherdatarequestfailures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "syncLossIndications",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsMsgStatsField, synclossindications),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_msg_stats_field__field_indices_by_name[] = {
  7,   /* field[7] = channelAccessFailures */
  0,   /* field[0] = joinAttempts */
  1,   /* field[1] = joinFails */
  8,   /* field[8] = macAckFailures */
  2,   /* field[2] = msgsAttempted */
  3,   /* field[3] = msgsSent */
  9,   /* field[9] = otherDataRequestFailures */
  10,   /* field[10] = syncLossIndications */
  4,   /* field[4] = trackingRequests */
  5,   /* field[5] = trackingResponseAttempts */
  6,   /* field[6] = trackingResponseSent */
};
static const ProtobufCIntRange smsgs_msg_stats_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor smsgs_msg_stats_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_msgStatsField",
  "SmsgsMsgStatsField",
  "SmsgsMsgStatsField",
  "",
  sizeof(SmsgsMsgStatsField),
  11,
  smsgs_msg_stats_field__field_descriptors,
  smsgs_msg_stats_field__field_indices_by_name,
  1,  smsgs_msg_stats_field__number_ranges,
  (ProtobufCMessageInit) smsgs_msg_stats_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_config_settings_field__field_descriptors[2] =
{
  {
    "reportingInterval",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigSettingsField, reportinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pollingInterval",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsConfigSettingsField, pollinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_config_settings_field__field_indices_by_name[] = {
  1,   /* field[1] = pollingInterval */
  0,   /* field[0] = reportingInterval */
};
static const ProtobufCIntRange smsgs_config_settings_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor smsgs_config_settings_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_configSettingsField",
  "SmsgsConfigSettingsField",
  "SmsgsConfigSettingsField",
  "",
  sizeof(SmsgsConfigSettingsField),
  2,
  smsgs_config_settings_field__field_descriptors,
  smsgs_config_settings_field__field_indices_by_name,
  1,  smsgs_config_settings_field__number_ranges,
  (ProtobufCMessageInit) smsgs_config_settings_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smsgs_sensor_msg__field_descriptors[10] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, cmdid),
    &smsgs_cmd_ids__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frameControl",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, framecontrol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tempSensor",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, tempsensor),
    &smsgs_temp_sensor_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lightSensor",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, lightsensor),
    &smsgs_light_sensor_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humiditySensor",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, humiditysensor),
    &smsgs_humidity_sensor_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgStats",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, msgstats),
    &smsgs_msg_stats_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "configSettings",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, configsettings),
    &smsgs_config_settings_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressureSensor",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, pressuresensor),
    &smsgs_pressure_sensor_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motionSensor",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, motionsensor),
    &smsgs_motion_sensor_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batterySensor",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmsgsSensorMsg, batterysensor),
    &smsgs_battery_sensor_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smsgs_sensor_msg__field_indices_by_name[] = {
  9,   /* field[9] = batterySensor */
  0,   /* field[0] = cmdId */
  6,   /* field[6] = configSettings */
  1,   /* field[1] = frameControl */
  4,   /* field[4] = humiditySensor */
  3,   /* field[3] = lightSensor */
  8,   /* field[8] = motionSensor */
  5,   /* field[5] = msgStats */
  7,   /* field[7] = pressureSensor */
  2,   /* field[2] = tempSensor */
};
static const ProtobufCIntRange smsgs_sensor_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor smsgs_sensor_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Smsgs_sensorMsg",
  "SmsgsSensorMsg",
  "SmsgsSensorMsg",
  "",
  sizeof(SmsgsSensorMsg),
  10,
  smsgs_sensor_msg__field_descriptors,
  smsgs_sensor_msg__field_indices_by_name,
  1,  smsgs_sensor_msg__number_ranges,
  (ProtobufCMessageInit) smsgs_sensor_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue smsgs_cmd_ids__enum_values_by_number[7] =
{
  { "Smsgs_cmdIds_configReq", "SMSGS_CMD_IDS__Smsgs_cmdIds_configReq", 1 },
  { "Smsgs_cmdIds_configRsp", "SMSGS_CMD_IDS__Smsgs_cmdIds_configRsp", 2 },
  { "Smsgs_cmdIds_trackingReq", "SMSGS_CMD_IDS__Smsgs_cmdIds_trackingReq", 3 },
  { "Smsgs_cmdIds_trackingRsp", "SMSGS_CMD_IDS__Smsgs_cmdIds_trackingRsp", 4 },
  { "Smsgs_cmdIds_sensorData", "SMSGS_CMD_IDS__Smsgs_cmdIds_sensorData", 5 },
  { "Smsgs_cmdIds_toggleLedReq", "SMSGS_CMD_IDS__Smsgs_cmdIds_toggleLedReq", 6 },
  { "Smsgs_cmdIds_toggleLedRsp", "SMSGS_CMD_IDS__Smsgs_cmdIds_toggleLedRsp", 7 },
};
static const ProtobufCIntRange smsgs_cmd_ids__value_ranges[] = {
{1, 0},{0, 7}
};
static const ProtobufCEnumValueIndex smsgs_cmd_ids__enum_values_by_name[7] =
{
  { "Smsgs_cmdIds_configReq", 0 },
  { "Smsgs_cmdIds_configRsp", 1 },
  { "Smsgs_cmdIds_sensorData", 4 },
  { "Smsgs_cmdIds_toggleLedReq", 5 },
  { "Smsgs_cmdIds_toggleLedRsp", 6 },
  { "Smsgs_cmdIds_trackingReq", 2 },
  { "Smsgs_cmdIds_trackingRsp", 3 },
};
const ProtobufCEnumDescriptor smsgs_cmd_ids__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Smsgs_cmdIds",
  "Smsgs_cmdIds",
  "SmsgsCmdIds",
  "",
  7,
  smsgs_cmd_ids__enum_values_by_number,
  7,
  smsgs_cmd_ids__enum_values_by_name,
  1,
  smsgs_cmd_ids__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue smsgs_data_fields__enum_values_by_number[9] =
{
  { "Smsgs_dataFields_tempSensor", "SMSGS_DATA_FIELDS__Smsgs_dataFields_tempSensor", 1 },
  { "Smsgs_dataFields_lightSensor", "SMSGS_DATA_FIELDS__Smsgs_dataFields_lightSensor", 2 },
  { "Smsgs_dataFields_humiditySensor", "SMSGS_DATA_FIELDS__Smsgs_dataFields_humiditySensor", 4 },
  { "Smsgs_dataFields_msgStats", "SMSGS_DATA_FIELDS__Smsgs_dataFields_msgStats", 8 },
  { "Smsgs_dataFields_configSettings", "SMSGS_DATA_FIELDS__Smsgs_dataFields_configSettings", 16 },
  { "Smsgs_dataFields_pressureSensor", "SMSGS_DATA_FIELDS__Smsgs_dataFields_pressureSensor", 32 },
  { "Smsgs_dataFields_toggleSettings", "SMSGS_DATA_FIELDS__Smsgs_dataFields_toggleSettings", 48 },
  { "Smsgs_dataFields_motionSensor", "SMSGS_DATA_FIELDS__Smsgs_dataFields_motionSensor", 64 },
  { "Smsgs_dataFields_batterySensor", "SMSGS_DATA_FIELDS__Smsgs_dataFields_batterySensor", 128 },
};
static const ProtobufCIntRange smsgs_data_fields__value_ranges[] = {
{1, 0},{4, 2},{8, 3},{16, 4},{32, 5},{48, 6},{64, 7},{128, 8},{0, 9}
};
static const ProtobufCEnumValueIndex smsgs_data_fields__enum_values_by_name[9] =
{
  { "Smsgs_dataFields_batterySensor", 8 },
  { "Smsgs_dataFields_configSettings", 4 },
  { "Smsgs_dataFields_humiditySensor", 2 },
  { "Smsgs_dataFields_lightSensor", 1 },
  { "Smsgs_dataFields_motionSensor", 7 },
  { "Smsgs_dataFields_msgStats", 3 },
  { "Smsgs_dataFields_pressureSensor", 5 },
  { "Smsgs_dataFields_tempSensor", 0 },
  { "Smsgs_dataFields_toggleSettings", 6 },
};
const ProtobufCEnumDescriptor smsgs_data_fields__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Smsgs_dataFields",
  "Smsgs_dataFields",
  "SmsgsDataFields",
  "",
  9,
  smsgs_data_fields__enum_values_by_number,
  9,
  smsgs_data_fields__enum_values_by_name,
  8,
  smsgs_data_fields__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue smsgs_status_values__enum_values_by_number[3] =
{
  { "Smsgs_statusValues_success", "SMSGS_STATUS_VALUES__Smsgs_statusValues_success", 0 },
  { "Smsgs_statusValues_invalid", "SMSGS_STATUS_VALUES__Smsgs_statusValues_invalid", 1 },
  { "Smsgs_statusValues_partialSuccess", "SMSGS_STATUS_VALUES__Smsgs_statusValues_partialSuccess", 2 },
};
static const ProtobufCIntRange smsgs_status_values__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex smsgs_status_values__enum_values_by_name[3] =
{
  { "Smsgs_statusValues_invalid", 1 },
  { "Smsgs_statusValues_partialSuccess", 2 },
  { "Smsgs_statusValues_success", 0 },
};
const ProtobufCEnumDescriptor smsgs_status_values__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Smsgs_statusValues",
  "Smsgs_statusValues",
  "SmsgsStatusValues",
  "",
  3,
  smsgs_status_values__enum_values_by_number,
  3,
  smsgs_status_values__enum_values_by_name,
  1,
  smsgs_status_values__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
